# Generated by Django 4.0.5 on 2022-07-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebCrawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='last_updated',
        ),
    ]
